# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:PGUSER:ScrumBut"
  password: "_env:PGPASS:ScrumBut"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:ScrumBut"
  poolsize: "_env:PGPOOLSIZE:10"

copyright: ""
#analytics: UA-YOURCODE

# OAuth settings for GitHub, defaulting to the "ScrumBut (staging)" application.
github-client-id: "_env:GITHUB_CLIENT_ID:3d4667bd36b0de1bdd14"
github-client-secret: "_env:GITHUB_CLIENT_SECRET:febd75e7c324391c116bb3665ceea19f473dbdef"
