#!/bin/bash

set -e
export SCRIPT_DIR=$(dirname "$0")

brew update
brew install postgresql

cabal update
cabal install -j alex happy yesod-bin
cabal install -j --only-dependencies --enable-tests

. "$SCRIPT_DIR/startdb"
