#!/bin/bash
#
# Deploys the current branch to Heroku. Any arguments (like --force) are passed
# through to `git push` unmodified.

set -e
export SCRIPT_DIR=$(dirname "$0")

branch=$(git symbolic-ref --short HEAD)
git push "$@" heroku "$branch:master"

heroku open
