#!/bin/bash
#
# Seeds development and production databases with required tables, and any test
# data.

set -e

createuser ScrumBut || true
createdb --owner=ScrumBut ScrumBut || true
createdb --owner=ScrumBut ScrumBut_test || true
